#!/bin/sh

# $FreeBSD$
#
# PROVIDE: movx 
# REQUIRE: NETWORK
# KEYWORD: shutdown

. /etc/rc.subr

name="movx"
rcvar="movx_enable"

# default values
: ${movx_enable="NO"}

root_path="/mnt/MOVX"

command=/usr/sbin/daemon

pidfile="/var/run/${name}.pid"
command_args="-t movx -f -T movx -P /var/run/movx.pid /usr/local/bin/python3.9 -m movx agent ${root_path}"

load_rc_config $name
run_rc_command "$1"

